services:
  redis:
    image: redis:7-alpine
    command: ["redis-server","--appendonly","yes"]
    restart: unless-stopped

  summarizer-api:
    build: .               # ← build from current folder
    image: summarizer:latest
    env_file: ./.env       # ← load env from top-level .env
    environment:
      QUEUE_URL: redis://redis:6379/0
      RESULTS_BUCKET: local://data/summaries
      TRANSCRIPTS_BASE: local://data/transcripts
    volumes:
      - ./asr-data:/app/data
    ports:
      - "9001:9000"
    depends_on:
      - redis
    restart: unless-stopped

  summarizer-worker:
    image: summarizer:latest
    command: ["python","-m","app.worker.worker"]
    env_file: ./.env
    environment:
      QUEUE_URL: redis://redis:6379/0
      RESULTS_BUCKET: local://data/summaries
      TRANSCRIPTS_BASE: local://data/transcripts
    volumes:
      - ./asr-data:/app/data
    depends_on:
      - redis
    restart: unless-stopped
